import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProviderWrapper } from "@/components/AuthProviderWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProviderWrapper>
            <header className="bg-gray-100 p-4 border-b mb-4">
              <nav className="flex gap-4">
                <a href="/dashboard" className="text-blue-600 hover:underline">Dashboard</a>
                <a href="/book" className="text-blue-600 hover:underline">Book</a>
              </nav>
            </header>
          {children}
        </AuthProviderWrapper>
      </body>
    </html>
  );
}
